% Lucky Numbers
%
% In number theory, a lucky number is a natural number in a set which
% is generated by a certain "sieve". This sieve is similar to the Sieve
% of Eratosthenes that generates the primes, but it eliminates numbers
% based on their position in the remaining set, instead of their value
% (or position in the initial set of natural numbers).
%
-module(lucky_numbers).

-export([go/1]).

-include_lib("eunit/include/eunit.hrl").

go(Size) ->
    Iterations = round(math:ceil(math:sqrt(Size))),
    go(Iterations, 2, lists:seq(1,Size)).

go(0, _, List) -> List;
go(Iterations, DeleteEvery, List) -> go(Iterations-1,DeleteEvery+1, sieve(DeleteEvery,List,[])).

sieve(DeleteEvery, Remainder, NewList) when length(Remainder) < DeleteEvery -> NewList++Remainder;
sieve(DeleteEvery, OldList, NewList) ->
    {Keep,[_Drop|Tail]} = lists:split(DeleteEvery-1, OldList),
    sieve(DeleteEvery,Tail,NewList++Keep).

go_test_() ->
    [
     ?_assertEqual([1], go(1)),
     ?_assertEqual([1,3,7,13,19], go(20)),
     ?_assertEqual([1,3,7,13,19,27,39,49,63,79,91], go(100))
    ].
